services:
  mysql:
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: player-db
      MYSQL_USER: player
      MYSQL_PASSWORD: player
    ports:
      - 3386:3306
    healthcheck:
      test: mysqladmin ping -h mysql -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
  player-rest:
    image: 'liye198995/player-rest:latest'
#    build: ../api
    ports:
      - 8888:8080
    depends_on:
      mysql:
        condition: service_healthy
        required: true

